[package]
name = "name_exchanger_rslib"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
name = "name_exchanger_rsdll"

[dependencies]
